### ISSUE TITLE
Add tests for encoding/decoding header on mapeo docs

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-schema#123]
We need to add tests for encoding and decoding the header (which now includes only the schemaType as a random generated id and the schema version).
There's the discussion of adding `createdAt` and `createdBy` to the header (see https://github.com/digidem/mapeo-core-next/issues/153), so if this ends up implemented, we should also test for that

**Comment by gmaclennan** [comment]
> There's the discussion of adding `createdAt` and `createdBy` to the header (see [digidem/mapeo-core-next#153](https://github.com/digidem/mapeo-core-next/issues/153)), so if this ends up implemented, we should also test for that

I didn't intend any of the options I described to mean to add to the header. I think these belong in the main block with everything else.

**Comment by tomasciccola** [comment]
oohh, missunderstanding from my part then!
