### ISSUE TITLE
Decode future schema versions without throwing

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-schema#168]
We should maintain the protobufs to be future-compatible, so we should not throw if the schema version does not match the one we are expecting. It would be good to do this for the MVP so that all public versions are future compatible.

**Comment by gmaclennan** [comment]
I think this is important to address for MVP for maximum compatibility. Throwing causes a record to be ignored by previous versions, but because protobuf is backwards and forwards compatible, I think it would be better if we decoded what we can from future versions. Would welcome @EvanHahn's thoughts on whether this really is important for MVP.

**Comment by EvanHahn** [comment]
I don't think we need to do this.

- `decode` and `decodeBlockPrefix` throw for unknown schemas (see [1]) and unknown schema versions (see [2]). I think this is good.[^1]
- `@mapeo/core` handles cases where `decode` and `decodeBlockPrefix` throw (see [3], [4]).

Therefore, I don't think this task is necessary. Does that seem right to you, @gmaclennan?

I could see adding some documentation to `decode` and `decodeBlockPrefix`, mentioning that they'll throw if they get an unrecognized schema (version)...maybe that's the task?

[^1]: I'd also accept them returning `null` or some result type.

[1]: https://github.com/digidem/mapeo-schema/blob/37bc87d396700e49eba74ff66f2de4c9357610cd/src/decode.ts#L84-L85
[2]: https://github.com/digidem/mapeo-schema/blob/37bc87d396700e49eba74ff66f2de4c9357610cd/src/decode.ts#L151-L155
[3]: https://github.com/digidem/mapeo-core-next/blob/b9feab5bb6badbd31d043abb2684d23866d616ba/src/index-writer/index.js#L84-L85
[4]: https://github.com/digidem/mapeo-core-next/blob/b9feab5bb6badbd31d043abb2684d23866d616ba/src/mapeo-project.js#L472

**Comment by gmaclennan** [comment]
I think we do need to do this.

- We are using protobuf for backwards compatibility, e.g. if we update a protobuf, then older clients should still be able to read the protobuf.
- If we update a protobuf in a backwards-compatible way, then currently we must not update the schemaVersion in the block prefix, because if we did, then older clients would not see data from newer clients (because decode would throw).
- If we don't update schemaVersion, then why have it?
- It is useful to know what version of a schema was used to create / encode a doc.

Suggestion:

1. We assume that all future encodings of a particular schema type are backwards compatible, so we _always_ try to decode.
2. If the encoding is not actually backwards compatible, the ts-proto decode will fail anyway.
3. Every time we make a change to the protobuf schema (e.g. add or remove a field) then we should increment the schemaversion.
4. We use schemaVersion for debugging where docs came from, e.g. fields we might expect to see.

**Comment by EvanHahn** [comment]
Ah, I think I misunderstood the point of schema versions. I assumed they were only incremented for breaking changes, not backwards-compatible ones.
