### ISSUE TITLE
Add `type` to observation refs (post-MVP, pre-migration)

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-schema#192]
Observations have a `refs` property that we do not yet use, which is used to link observations to nodes and ways. This was used (not very often) in Mapeo Legacy when a user was creating territory points from observations. I can't remember the code exactly, but I _think_ the observations were displayed in the territory view, and if they are edited, they become a "node", and the observation has a ref to that node.

Because of our new index structure, we have no global `docId` index, and we don't assert that ids are globally unique (although in general, they are, but not always - more than one data type uses deviceId for the docId. Therefore refs need to reference a document type too.

I would also be ok just removing this property for MVP, if that's quicker than changing it, and maybe preferable to have this hanging around as a "legacy" refs format forever, even if we know it's (probably) never actually used.

See tracks for how we should do it: 

- https://github.com/digidem/mapeo-schema/blob/f6d93ca456f1059d118dff2d094ceed312fcc2e9/schema/track/v1.json#L64-L85
- https://github.com/digidem/mapeo-schema/blob/main/proto/track/v1.proto#L24-L27

We will need this to ensure we import all the data during migration, even if we haven't defined what "nodes" are at that point. I don't think there is any case where an observation is linked to a way - there was never a way to create that ref in any Mapeo Legacy tooling.

**Comment by EvanHahn** [comment]
Personally, I think we should remove it until we need it. Protobuf should make that easy to do. Does that seem like a reasonable approach?

**Comment by gmaclennan** [comment]
Yes, agreed.
