### ISSUE TITLE
Remove `optional` fields from protobufs unless they're truly optional

### ISSUE THREAD

**Issue by EvanHahn** [digidem/mapeo-schema#200]

**Comment by tomasciccola** [comment]
here's a dump of `grep "optional" proto/**/*`:
```
proto/common/v1.proto:  optional bytes docId = 1 [(required) = true];
proto/deviceInfo/v1.proto:  optional DeviceType deviceType = 6;
proto/field/v1.proto:  optional string tagKey = 5 [(required) = true];
proto/field/v1.proto:  optional string label = 7 [(required) = true];
proto/field/v1.proto:  optional Appearance appearance = 8;
proto/field/v1.proto:  optional bool snakeCase = 9;
proto/field/v1.proto:  optional bool universal = 11;
proto/field/v1.proto:  optional string placeholder = 12;
proto/field/v1.proto:  optional string helperText = 13;
proto/observation/v1.proto:  optional double lat = 5;
proto/observation/v1.proto:  optional double lon = 6;
proto/observation/v1.proto:    optional bool manualLocation = 1;
proto/observation/v1.proto:      optional Coords coords = 3;
proto/observation/v1.proto:    optional Position position = 3;
proto/observation/v1.proto:    optional Position lastSavedPosition = 4;
proto/observation/v1.proto:    optional PositionProvider positionProvider = 5;
proto/observation/v1.proto:  optional Metadata metadata = 9;
proto/preset/v1.proto:  optional IconRef iconRef = 11;
proto/projectSettings/v1.proto:  optional DefaultPresets defaultPresets = 2;
proto/projectSettings/v1.proto:  optional ConfigMetadata configMetadata = 3;
proto/projectSettings/v1.proto:  optional string name = 4;
proto/track/v1.proto:      optional double altitude = 3;
proto/track/v1.proto:      optional double heading = 4;
proto/track/v1.proto:      optional double speed = 5;
proto/track/v1.proto:      optional double accuracy = 6;
```
I'm wondering which fields are TRULY optional. After I know that then I can move forward with the issue

**Comment by EvanHahn** [comment]
_Please double-check my understandings here_, but I think this is the breakdown:

## Things I think we should change

It seems like no required fields should be optional, so we should change these:

    proto/common/v1.proto:10:  optional bytes docId = 1 [(required) = true];
    proto/field/v1.proto:17:  optional string tagKey = 5 [(required) = true];
    proto/field/v1.proto:26:  optional string label = 7 [(required) = true];

These fields seem like they gain nothing from having an `undefined` value. It's okay if someone omits them (there's a reasonable default) but I think they should always be set at read time:

    proto/field/v1.proto:39:  optional bool universal = 11;
    proto/field/v1.proto:41:  optional string helperText = 13;
    proto/observation/v1.proto:41:    optional bool manualLocation = 1;

These fields seem like we always want them:

    proto/observation/v1.proto:18:  optional double lat = 5;
    proto/observation/v1.proto:19:  optional double lon = 6;
    proto/observation/v1.proto:55:      optional Coords coords = 3;

I _think_ observations should always have a preset? Not sure about this one.

    proto/observation/v1.proto:71:  optional PresetRef presetRef = 10;

Similarly, I think all presets should have an icon:

    proto/preset/v1.proto:24:  optional IconRef iconRef = 11;

## Things I _don't_ think we need to change

For `DeviceInfo`, I think it's fine that `deviceType` is optional. No changes needed.

    proto/deviceInfo/v1.proto:24:  optional DeviceType deviceType = 6;

These `Field` values only make sense for text types, so I think it's okay for them to be optional.

    proto/field/v1.proto:32:  optional Appearance appearance = 8;
    proto/field/v1.proto:33:  optional bool snakeCase = 9;
    proto/field/v1.proto:40:  optional string placeholder = 12;

These `Observation` metadata values seem like they can be skipped:

    proto/observation/v1.proto:65:    optional Position position = 3;
    proto/observation/v1.proto:66:    optional Position lastSavedPosition = 4;
    proto/observation/v1.proto:67:    optional PositionProvider positionProvider = 5;
    proto/observation/v1.proto:69:  optional Metadata metadata = 9;

I assume we don't always know these values for `Track`s, so we can keep these as optional:

    proto/track/v1.proto:48:      optional double altitude = 3;
    proto/track/v1.proto:49:      optional double heading = 4;
    proto/track/v1.proto:50:      optional double speed = 5;
    proto/track/v1.proto:51:      optional double accuracy = 6;

You probably know whether these are required or not, but I _think_ they're all truly optional:

    proto/projectSettings/v1.proto:30:  optional DefaultPresets defaultPresets = 2;
    proto/projectSettings/v1.proto:31:  optional ConfigMetadata configMetadata = 3;
    proto/projectSettings/v1.proto:32:  optional string name = 4;

**Comment by tomasciccola** [comment]
Right, thanks for this. 


> I _think_ observations should always have a preset? Not sure about this one.

`presetRef` was added recently and I think they are always optional (mostly also because there's nothing set up to reference a preset when adding an observation). So I think _for now_ it can be optional and if in the future we actually use this, it can become mandatory

**Comment by tomasciccola** [comment]
Wondering about correspondence with JSONSchema. Are non-optional values `required` in JSONSchema? I would say **yes** but I see there are some discrepancies. e.g. metadata is optional on the proto but required on the jsonSchema

**Comment by EvanHahn** [comment]
> Wondering about correspondence with JSONSchema. Are non-optional values `required` in JSONSchema? I would say **yes** but I see there are some discrepancies. e.g. metadata is optional on the proto but required on the jsonSchema

Not sure. I think my "algorithm" would be:

1. I think if it's `required` in the JSON Schema, it should not be `optional` in the proto.
2. If it has a default value in the JSON Schema, it should not be `optional` in the proto.
3. Otherwise..._probably_ optional in the proto? I think?
