### ISSUE TITLE
Remove `attachments` field from tracks schema

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-schema#223]
From an end-user perspective, it's not immediately clear as to why it exists in the first place. For now, it seems sufficient to reference attachments that are associated to the observations that are referenced by the `observationRefs` field.

**Comment by EvanHahn** [comment]
Should we do this before MVP? It should be quick.

**Comment by achou11** [comment]
> Should we do this before MVP? It should be quick.

yeah i think it'd be worth doing for MVP
