### ISSUE TITLE
Source for earlier schema versions?

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-schema#27]
In working on data migration I realized I haven't seen any Observation schemas earlier than v4, though data from an example project I've been working with is v3.

@gmaclennan Where would I find these older schemas?

It would be ideal if they were included in this repo as well.

**Comment by tomasciccola** [comment]
re pinging @gmaclennan to see if we have a source for Observation v3. A syncfile generated on latest Mapeo Desktop seems to have this version. This is kinda necessary for migration work

**Comment by gmaclennan** [comment]
Unfortunately schemas were not properly documented previously. I can find this reference in the Mapeo Mobile code: https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/%40types/mapeo-schema.d.ts#L41 from reading the source code of the apps, it looks like we have always been writing observations with schemaVersion:3. I think the only way to truly know the schemas of old data is to look through older versions of Mapeo Mobile to see the shape/type of observations that were created. All observations can only have been created with mapeo mobile - desktop only allows editing.

**Comment by gmaclennan** [comment]
I do remember writing some kind of conversion code a long time ago between schema versions 1 & 2 & 3, but I can't find it anywhere - the dependency tree for old mapeo core was very confusing and it could be in any of a number of dependencies but I can't see it in mapeo-server or mapeo-core or kappa-osm or osm-p2p or osm-p2p-db

**Comment by tomasciccola** [comment]
ok, thanks for the answer! Good to have a source to look at and at the same time I was basically looking at the shape of observations from legacy mapeo to get a sense of it. 
I wonder if it makes sense to, after analysing the shape/type of a doc, add that schema to old/schema so that we can validate old docs when doing migration. This can maybe help to find outliers
