### ISSUE TITLE
handle bad schema versions in encode/decode functions

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-schema#30]
Right now the encode/decode functions don't check if a schema version is valid.

Maybe we need a lookup table similar to schemasPrefix.js? It could probably be generated as part of the generate.js script

**Comment by tomasciccola** [comment]
With code generation adding schemaVersions array to the `schemasPrefix.js` should be unnecessary, since generated types take into account type AND version (so Observation v4, has a type Observation_4). Having ```
ProtobufSchemas[`${type}_${schemaVersion}`]``` as `undefined` means an invalid `schemaVersion` or `type`

**Comment by sethvincent** [comment]
Nice, that makes sense :+1:

**Comment by tomasciccola** [comment]
Closed with [https://github.com/digidem/mapeo-schema/pull/32](this PR)
