### ISSUE TITLE
Nested schema proposal

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-schema#35]
I was talking with @achou11 today about the client API, and we agreed that it could be a nicer DX to nest user-editable props in the schema. This would mean keeping the [common props](https://github.com/digidem/mapeo-schema/blob/master/schema/common/v1.json) at the top level, and other props under a `value` prop, e.g.

```js
{
  id: 'e0679df6fa62fb2b5a37600207be9e7e'
  version: '96e9437a759ef4ebeef0809ba1dda3d8'
  created_at: 1671840000000,
  edited_at: 1677530901091,
  links: ['be8d244baeaffe5558e636860a9f14a2'],
  value: {
    lat: 58.2416,
    lon: -6.6616,
    tags: {},
    refs: [],
    attachments: []
}
```

The advantage of doing this that when editing this object, it is clearer what can be changed and what cannot - the front-end can edit and save everything under `value`, but everything top level is set by the server. An update method e.g. `mapeo.observation.update(id, value)` would only need to pass the value, rather than the entire object, which might be confusing anyway because passing e.g. the `version` prop would not actually update that prop.

We don't need to also change this in the protobuf schema, but having the same structure in protobuf might be a performance win.

**Comment by sethvincent** [comment]
Should `links` be in `value`? If the links need to be set on update I guess so. That leaves only a few properties that aren't in `value`. 

It seems like a fine change, though I'm not sure it has a substantial payoff. It has the side effect that when accessing properties some have to be prefixed with `value` and some don't, which isn't a great tradeoff when building components.

We could just make it so properties that are managed by core can't be changed on update (we should make sure that's the case anyway).

**Comment by tomasciccola** [comment]
I'm gonna start working on this next week. Work should be minimal since its just mean avoiding flattening schemas (happening [here](https://github.com/digidem/mapeo-schema/blob/a3f79e0fcde869a27d33b65a7981cdf0c0e56998/index.js#L45) and [here](https://github.com/digidem/mapeo-schema/blob/a3f79e0fcde869a27d33b65a7981cdf0c0e56998/index.js#L65).

Do we still think this is the way to go? Could there be shortcomings to this?? @gmaclennan

**Comment by tomasciccola** [comment]
> We could just make it so properties that are managed by core can't be changed on update (we should make sure that's the case anyway).

How do you think we can solve for this then? maybe using proxies that intercept a setter?

**Comment by gmaclennan** [comment]
After @achou11 and I met and discussed the API, we've concluded not to do this, although we do now nest common properties in the Protobuf encoding, the decoded values are flat. This simplifies writing into the SQLite index tables.
