### ISSUE TITLE
Consider changing `type` in schemas to `schemaType` (excluding field schema)

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-schema#37]
The field schema has a `type` property already (I think inherited from id editor / presets?) that conflicts with the `type` property we use as the schema type like `observation`.

We could:
- change the field `type` property to something else (but probably not because of interop with id editor)
- change our schema-focused property to something like `schemaType` to match `schemaVersion`
- _some third option?_

**Comment by tomasciccola** [comment]
yeah, I think the second option is the best one. Should add code to handle older versions so that `schemaType` is transform to `type` when encoding and vise versa when decoding

**Comment by sethvincent** [comment]
closed by #41
