### ISSUE TITLE
Finalize message type GUIDs

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-schema#64]

**Comment by tomasciccola** [comment]
- [ ] Generate random GUIDs for every record type. This is stored on `schemasPrefix.js` as 
```js
{[schemaType]:{ dataTypeId: string, schemaVersions: [number]}}
```
(Can we avoid future modifications of this id's? One can be a runtime check where `schemasPrefix` is an immutable Object (Object.freeze?). But also we can freeze the file in [git](https://stackoverflow.com/questions/23528104/how-to-freeze-a-file-in-a-repository) ?)
- [ ] Revise and ***document*** criteria for `dataTypeId` size taking into account probabilities of hash collisions in terms of number of posible `dataTypeId`s generated
- [ ] Document format of header of saved records
